aws:
  accessKeyId: blank
  secretKey: blank
  dynamodb:
    endpoint: http://localhost:8854
cloud:
  aws:
    region:
      static: us-east-1
      auto: false
server:
  port: 9016

spring:
  main:
    allow-bean-definition-overriding: true
