apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-leader
  labels:
    app: backend
    role: leader
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        role: leader
        tier: backend
    spec:
      containers:
        - name: leader
          image: '{{ .Values.image.repository}}:{{ .Values.image.tag}}'
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
          ports:
            - containerPort: 9999
