apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    tier: api-service
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
      nodePort: 30157
  type: LoadBalancer