apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend-api
          ports:
            - containerPort: 9999
          image: 'michalczuk/spring-redis-app:1.0'
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: '500m'
              memory: '600Mi'
            requests:
              cpu: '400m'
              memory: '500Mi'
          env:
            - name: REDIS_URI
              value: redis://rediscache-service
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://user:pass@mongodb-service/mongodb
