apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-leader
  labels:
    app: backend
    role: leader
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        role: leader
        tier: backend
    spec:
      containers:
        - name: leader
          image: 'michalczuk/spring-redis-app:1.0'
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: '500m'
              memory: '600Mi'
            requests:
              cpu: '400m'
              memory: '500Mi'
          env:
            - name: REDIS_URI
              value: redis://rediscache
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://user:pass@mongo/mongodb
          ports:
            - containerPort: 9999
