apiVersion: apps/v1
kind: Deployment
metadata:
  name: rediscache-deployment
spec:
  selector:
    matchLabels:
      app: rediscache
  replicas: 1
  template:
    metadata:
      labels:
        app: rediscache
    spec:
      containers:
        - name: rediscache
          image: redis
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: rediscache-service
spec:
  selector:
    app: rediscache
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
